INSERT INTO USER (ID, EMAIL, NAME, PASSWORD, USER_ID) VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'yds@kt.com', '윤동섭', '1111', 'yoon.ds');
INSERT INTO USER (ID, EMAIL, NAME, PASSWORD, USER_ID) VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'lee.hh@kt.com', '이현하', '2222', 'lee.hh');
INSERT INTO USER (ID, EMAIL, NAME, PASSWORD, USER_ID) VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'kim.dj@kt.com', '김다정', '3333', 'kim.dj');
INSERT INTO QUESTION (ID, CONTENTS, CREATE_DATE, TITLE, WRITER_ID) VALUES (QUESTION_SEQ.NEXTVAL, '게시물 작성 테스트', SYSDATE, '테스트용 게시물', 1);
INSERT INTO QUESTION (ID, CONTENTS, CREATE_DATE, TITLE, WRITER_ID) VALUES (QUESTION_SEQ.NEXTVAL, '김다정 작성용', SYSDATE, '김다정 왔다감', 3);