INSERT INTO USER (ID, EMAIL, NAME, PASSWORD, USER_ID) VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'yds@kt.com', '윤동섭', '1111', 'yoon.ds');
INSERT INTO USER (ID, EMAIL, NAME, PASSWORD, USER_ID) VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'lee.hh@kt.com', '이현하', '2222', 'lee.hh');
INSERT INTO USER (ID, EMAIL, NAME, PASSWORD, USER_ID) VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'kim.dj@kt.com', '김다정', '3333', 'kim.dj');